all:

install:
	mkdir -p /opt/md2html/
	mkdir -p /opt/md2html/libs/
	mkdir -p /opt/md2html/src/
	install libs/* /opt/md2html/libs/
	install src/* /opt/md2html/src/
	install md2html.php /usr/bin/md2html

remove:
	rm -rf /opt/md2html
	rm /usr/bin/md2html
